### ISSUE TITLE
Retos :D

### ISSUE THREAD

**Issue by jevillanueva** [Pomca-laura/psg-example#1]
Felicidades estas avanzando bien!! :D

Los retos estan bien, solo una consideración 

cuando se trata de archivos Markdown esperamos que sean textos con formato con titulos cuerpos listados, negrillas cursivas, es una forma de darle formato a la presentación ya que se renderizan en HTML

Vas muy bien sigue adelante!! :D

**Comment by Pomca-laura** [comment]
Holaaaaaaaaaaaa

Mil gracias por la retroalimentación. Haré los cambios necesarios.

Un abrazo y gracias por su excelente trabajo y actitud.


Cordialmente,





*Laura Catalina Vasquez Salazar*




*PRESERVA EL MEDIO AMBIENTE*


*Sea amable con el medio ambiente: no imprima este correo a menos que sea
completamente necesario.*
